{% set name = "pdftotext" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdftotext-{{ version }}.tar.gz
  sha256: 2a9aa89bc62022408781b39d188fabf5a3ad1103b6630f32c4e27e395f7966ee
  patches:
    - setup.patch

build:
  number: 7
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - pkg-config
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - poppler
  run:
    - python
    - poppler

test:
  imports:
    - pdftotext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jalan/pdftotext
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple PDF text extraction
  description: |
    Simple PDF text extraction
  doc_url: https://github.com/jalan/pdftotext
  dev_url: https://github.com/jalan/pdftotext

extra:
  recipe-maintainers:
    - jan-janssen
