{% set name = "pdftotext" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdftotext-{{ version }}.tar.gz
  sha256: efbbfb14cf37ed7ab2c71936bae44707dfed6bb3be7ea5214e9c44c8c258c7af

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - pkg-config
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - poppler
  run:
    - python
    - poppler

test:
  imports:
    - pdftotext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jalan/pdftotext
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple PDF text extraction
  description: |
    Simple PDF text extraction
  doc_url: https://github.com/jalan/pdftotext
  dev_url: https://github.com/jalan/pdftotext

extra:
  recipe-maintainers:
    - jan-janssen
