{% set name = "pdftotext" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pdftotext-{{ version }}.tar.gz
  sha256: c3652b19154e145515a8bfa953fc6136338ed92337bdccbb53fe0d88013b1aaa
  patches:
    - setup.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pkg-config
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
    - poppler
  run:
    - python
    - poppler

test:
  imports:
    - pdftotext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jalan/pdftotext
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple PDF text extraction
  description: |
    Simple PDF text extraction
  doc_url: https://github.com/jalan/pdftotext
  dev_url: https://github.com/jalan/pdftotext

extra:
  recipe-maintainers:
    - jan-janssen
