{% set name = "pdftotext" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdftotext-{{ version }}.tar.gz
  sha256: a067c121654917ecbe07fbd71c807c34bbdb1ea029e269ddd11925ee7e191d3f
  patches:
    - setup.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - pkg-config
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - poppler
  run:
    - python
    - poppler

test:
  imports:
    - pdftotext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jalan/pdftotext
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple PDF text extraction
  description: |
    Simple PDF text extraction
  doc_url: https://github.com/jalan/pdftotext
  dev_url: https://github.com/jalan/pdftotext

extra:
  recipe-maintainers:
    - jan-janssen
